apiVersion: v1
kind: Service
metadata:
  name: fsd-service
  namespace: ai-tutor
  labels:
    app: ai-tutor
    subject: fsd
spec:
  selector:
    app: ai-tutor
    subject: fsd
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
