apiVersion: v1
kind: Service
metadata:
  name: dma-service
  namespace: ai-tutor
  labels:
    app: ai-tutor
    subject: dma
spec:
  selector:
    app: ai-tutor
    subject: dma
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
