apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsd-chroma-pvc
  namespace: ai-tutor
  labels:
    app: fsd-chroma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fcs-chroma-pvc
  namespace: ai-tutor
  labels:
    app: fcs-chroma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dma-chroma-pvc
  namespace: ai-tutor
  labels:
    app: dma-chroma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
