apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/nasttolm/ai-tutor-backend
    newTag: latest
  - name: ghcr.io/nasttolm/ai-tutor-frontend
    newTag: latest
