apiVersion: v1
kind: Service
metadata:
  name: fcs-service
  namespace: ai-tutor
  labels:
    app: ai-tutor
    subject: fcs
spec:
  selector:
    app: ai-tutor
    subject: fcs
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
